# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hello.HelloReq" do
    optional :msg, :string, 1
  end
  add_message "hello.HelloRes" do
    optional :msg, :string, 1
  end
end

module Hello
  HelloReq = Google::Protobuf::DescriptorPool.generated_pool.lookup("hello.HelloReq").msgclass
  HelloRes = Google::Protobuf::DescriptorPool.generated_pool.lookup("hello.HelloRes").msgclass
end
